spring.application.name=Promptify
server.port=8080
spring.datasource.url=jdbc:postgresql://db.byfsovpajxhxlwlzfyri.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Promtify@5252
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

clipdrop.api.key=7d1f1d4d90b73347a0cd5773c569db0a3691247b4ce6a40edada3a29e9e8a668a3c6cb3e984bed50d845057be7d9c20a


razorpay.key.id=rzp_test_RY5jWcyGij7WMu
razorpay.key.secret=WMf8G2Eir9QDKJle7Bl0skOR
